name: Daily Job Search

on:
  schedule:
    # 11:00 AM IST
    - cron: "30 5 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  search_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Job Finder
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python main.py

      - name: Commit updated sent_jobs.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add data/sent_jobs.json

          git diff --cached --quiet || git commit -m "Update tracked jobs"

          git push